name: entao_dutil
description: Utils for dart.
version: 2.3.4
repository: https://github.com/yangentao/entao_dutil
homepage: https://github.com/yangentao/entao_dutil

environment:
  sdk: ^3.7.0
resolution: workspace

dependencies:
  intl: ^0.20.2
  uuid: ^4.5.2
  collection: ^1.19.1
  os_detect: ^2.0.3
  async: ^2.13.0


  entao_lint: ^1.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  println: ^1.0.4
