name: entao_dutil
description: Utils for dart.
version: 2.0.9
repository: https://github.com/yangentao/entao_dutil
homepage: https://github.com/yangentao/entao_dutil

environment:
  sdk: ^3.5.0

dependencies:
  intl: ^0.20.2
  uuid: ^4.5.2
  collection: ^1.19.1
  os_detect: ^2.0.3
  entao_lint: ^1.0.1
  any_call: ^1.0.1
  println: ^1.0.4

  entao_range: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
